# Generated by Django 3.1.1 on 2020-09-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='projects/%Y/%m/')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('technology', models.CharField(max_length=30)),
                ('deploy', models.URLField(blank=True)),
                ('source', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('aimed', 'Aimed'), ('inprogress', 'In-Progress'), ('completed', 'Completed')], max_length=10)),
            ],
        ),
    ]
