# Generated by Django 3.1.1 on 2020-09-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangwe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('targeted', 'Targeted'), ('inprogress', 'In-Progress'), ('completed', 'Completed')], max_length=10),
        ),
    ]
